runtime: nodejs18
service: bci-marketplace

env_variables:
  NODE_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup 